In [2]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import math
from mpl_toolkits.mplot3d import Axes3D
from random import random
#from mpl_toolkits.mplot3d import axes3d
import matplotlib.pyplot as plt
import pandas as pd

<h1>Naive Bayes Classifier</h1>

Naive Bayes is one of the simplest supervised ML algorithms meanwhile very efficient and also is able to learn fast and make a quick prediction, therefore it is so useful and popular.
Naive Bayes contains two words Naive and Bayes, Bayes because it is built on Bayes Theorem, and Naive because it assumes that features are independent even if they actually are interdependent.It is simple but very powerful and works well with large datasets and sparse matrices. It works really well on text classification problems, and spam filtering.

<h2 id='bayes_theorem'> Bayes Theorem </h2>

Bayes theorem describes a probability of an event, based on prior knowledge of conditions that might be related to an event.
First, let's take the formula of conditional probability and try to derive Bayes Theorem:

$$p(A|B) = p(B\cap A)/p(B)$$
probability of event A given B, meaning what is the probability of A when event B is already taken place, wich is eqaul to quals probability of A intersection B (the probability of both A and B events are taken place) divided by probability of B.
we have the same for probability of event B given event A $$p(B|A) = p(A\cap B)/p(A)$$
the  $p(A\cap B)$ and  $p(B\cap A)$ are basicaly the same. Since they are the same, we can get two formulas and move denominator to the left of the equation,and equate them 
$$ p(B|A)p(A) = p(A\cap B) = p(B \cap A) = p(A|B)p(B) $$

So, when we want to find probability of A given B we can write our equation this way: <br>
$P(A|B) = P(B|A) * P(A) / P(B)$, and this is the equation of Bayes Theorem

* P(A|B) is the posterior probability of class (target) given predictor (attribute).
* P(B) is the prior probability of class.
* P(B|A) is the likelihood which is the probability of predictor given class.
* P(A) is the prior probability of predictor.

In [61]:
iris = pd.read_csv("../../../resources/data/golf_df.csv")  
iris

     Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no

In [59]:
c =iris['Play'].value_counts().to_numpy()

In [47]:
probability = c / c.sum()
probability

array([0.64285714, 0.35714286])

In [64]:
#k = iris.loc['Play']=='No' #loc['viper']
#.groupby('Outlook').count()
rslt_df = iris[iris['Play'] == 'yes'] 
rslt_df

     Outlook Temperature Humidity  Windy Play
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
6   overcast        cool   normal   True  yes
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes

In [72]:
iris.groupby('Outlook').count()

          Temperature  Humidity  Windy  Play
Outlook
overcast            4         4      4     4
rainy               5         5      5     5
sunny               5         5      5     5

In [71]:
rslt_df.groupby('Outlook').count()

          Temperature  Humidity  Windy  Play
Outlook
overcast            4         4      4     4
rainy               3         3      3     3
sunny               2         2      2     2

<h2> References </h2>
* <a href='https://towardsdatascience.com/implementing-naive-bayes-algorithm-from-scratch-python-c6880cfc9c41'>naive <br>
* <a href='https://prwatech.in/blog/machine-learning/naive-bayes-classifier-in-machine-learning/'> Indian Naive Bayes </a>